//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.ServiceReferenceA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EAlumno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EAlumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private int EdadField;
        
        private int SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceA.WebServiceAlumnSoap")]
    public interface WebServiceAlumnSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eAlumno del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear", ReplyAction="*")]
        Negocio.ServiceReferenceA.CrearResponse Crear(Negocio.ServiceReferenceA.CrearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear", ReplyAction="*")]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.CrearResponse> CrearAsync(Negocio.ServiceReferenceA.CrearRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarRut", ReplyAction="*")]
        Negocio.ServiceReferenceA.BuscarRutResponse BuscarRut(Negocio.ServiceReferenceA.BuscarRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarRut", ReplyAction="*")]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.BuscarRutResponse> BuscarRutAsync(Negocio.ServiceReferenceA.BuscarRutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarId", ReplyAction="*")]
        Negocio.ServiceReferenceA.BuscarIdResponse BuscarId(Negocio.ServiceReferenceA.BuscarIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarId", ReplyAction="*")]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.BuscarIdResponse> BuscarIdAsync(Negocio.ServiceReferenceA.BuscarIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eAlumno del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        Negocio.ServiceReferenceA.ActualizarResponse Actualizar(Negocio.ServiceReferenceA.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.ActualizarResponse> ActualizarAsync(Negocio.ServiceReferenceA.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        bool Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        Negocio.ServiceReferenceA.MostrarResponse Mostrar(Negocio.ServiceReferenceA.MostrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.MostrarResponse> MostrarAsync(Negocio.ServiceReferenceA.MostrarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Crear", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.CrearRequestBody Body;
        
        public CrearRequest() {
        }
        
        public CrearRequest(Negocio.ServiceReferenceA.CrearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Negocio.ServiceReferenceA.EAlumno eAlumno;
        
        public CrearRequestBody() {
        }
        
        public CrearRequestBody(Negocio.ServiceReferenceA.EAlumno eAlumno) {
            this.eAlumno = eAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearResponse", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.CrearResponseBody Body;
        
        public CrearResponse() {
        }
        
        public CrearResponse(Negocio.ServiceReferenceA.CrearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CrearResponseBody {
        
        public CrearResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarRut", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.BuscarRutRequestBody Body;
        
        public BuscarRutRequest() {
        }
        
        public BuscarRutRequest(Negocio.ServiceReferenceA.BuscarRutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public BuscarRutRequestBody() {
        }
        
        public BuscarRutRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarRutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.BuscarRutResponseBody Body;
        
        public BuscarRutResponse() {
        }
        
        public BuscarRutResponse(Negocio.ServiceReferenceA.BuscarRutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Negocio.ServiceReferenceA.EAlumno BuscarRutResult;
        
        public BuscarRutResponseBody() {
        }
        
        public BuscarRutResponseBody(Negocio.ServiceReferenceA.EAlumno BuscarRutResult) {
            this.BuscarRutResult = BuscarRutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarId", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.BuscarIdRequestBody Body;
        
        public BuscarIdRequest() {
        }
        
        public BuscarIdRequest(Negocio.ServiceReferenceA.BuscarIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public BuscarIdRequestBody() {
        }
        
        public BuscarIdRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.BuscarIdResponseBody Body;
        
        public BuscarIdResponse() {
        }
        
        public BuscarIdResponse(Negocio.ServiceReferenceA.BuscarIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Negocio.ServiceReferenceA.EAlumno BuscarIdResult;
        
        public BuscarIdResponseBody() {
        }
        
        public BuscarIdResponseBody(Negocio.ServiceReferenceA.EAlumno BuscarIdResult) {
            this.BuscarIdResult = BuscarIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.ActualizarRequestBody Body;
        
        public ActualizarRequest() {
        }
        
        public ActualizarRequest(Negocio.ServiceReferenceA.ActualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Negocio.ServiceReferenceA.EAlumno eAlumno;
        
        public ActualizarRequestBody() {
        }
        
        public ActualizarRequestBody(Negocio.ServiceReferenceA.EAlumno eAlumno) {
            this.eAlumno = eAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.ActualizarResponseBody Body;
        
        public ActualizarResponse() {
        }
        
        public ActualizarResponse(Negocio.ServiceReferenceA.ActualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarResult;
        
        public ActualizarResponseBody() {
        }
        
        public ActualizarResponseBody(bool ActualizarResult) {
            this.ActualizarResult = ActualizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mostrar", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.MostrarRequestBody Body;
        
        public MostrarRequest() {
        }
        
        public MostrarRequest(Negocio.ServiceReferenceA.MostrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarRequestBody {
        
        public MostrarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Negocio.ServiceReferenceA.MostrarResponseBody Body;
        
        public MostrarResponse() {
        }
        
        public MostrarResponse(Negocio.ServiceReferenceA.MostrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Negocio.ServiceReferenceA.EAlumno[] MostrarResult;
        
        public MostrarResponseBody() {
        }
        
        public MostrarResponseBody(Negocio.ServiceReferenceA.EAlumno[] MostrarResult) {
            this.MostrarResult = MostrarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAlumnSoapChannel : Negocio.ServiceReferenceA.WebServiceAlumnSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAlumnSoapClient : System.ServiceModel.ClientBase<Negocio.ServiceReferenceA.WebServiceAlumnSoap>, Negocio.ServiceReferenceA.WebServiceAlumnSoap {
        
        public WebServiceAlumnSoapClient() {
        }
        
        public WebServiceAlumnSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAlumnSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAlumnSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAlumnSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Negocio.ServiceReferenceA.CrearResponse Negocio.ServiceReferenceA.WebServiceAlumnSoap.Crear(Negocio.ServiceReferenceA.CrearRequest request) {
            return base.Channel.Crear(request);
        }
        
        public void Crear(Negocio.ServiceReferenceA.EAlumno eAlumno) {
            Negocio.ServiceReferenceA.CrearRequest inValue = new Negocio.ServiceReferenceA.CrearRequest();
            inValue.Body = new Negocio.ServiceReferenceA.CrearRequestBody();
            inValue.Body.eAlumno = eAlumno;
            Negocio.ServiceReferenceA.CrearResponse retVal = ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).Crear(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.CrearResponse> Negocio.ServiceReferenceA.WebServiceAlumnSoap.CrearAsync(Negocio.ServiceReferenceA.CrearRequest request) {
            return base.Channel.CrearAsync(request);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServiceReferenceA.CrearResponse> CrearAsync(Negocio.ServiceReferenceA.EAlumno eAlumno) {
            Negocio.ServiceReferenceA.CrearRequest inValue = new Negocio.ServiceReferenceA.CrearRequest();
            inValue.Body = new Negocio.ServiceReferenceA.CrearRequestBody();
            inValue.Body.eAlumno = eAlumno;
            return ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).CrearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Negocio.ServiceReferenceA.BuscarRutResponse Negocio.ServiceReferenceA.WebServiceAlumnSoap.BuscarRut(Negocio.ServiceReferenceA.BuscarRutRequest request) {
            return base.Channel.BuscarRut(request);
        }
        
        public Negocio.ServiceReferenceA.EAlumno BuscarRut(string rut) {
            Negocio.ServiceReferenceA.BuscarRutRequest inValue = new Negocio.ServiceReferenceA.BuscarRutRequest();
            inValue.Body = new Negocio.ServiceReferenceA.BuscarRutRequestBody();
            inValue.Body.rut = rut;
            Negocio.ServiceReferenceA.BuscarRutResponse retVal = ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).BuscarRut(inValue);
            return retVal.Body.BuscarRutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.BuscarRutResponse> Negocio.ServiceReferenceA.WebServiceAlumnSoap.BuscarRutAsync(Negocio.ServiceReferenceA.BuscarRutRequest request) {
            return base.Channel.BuscarRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServiceReferenceA.BuscarRutResponse> BuscarRutAsync(string rut) {
            Negocio.ServiceReferenceA.BuscarRutRequest inValue = new Negocio.ServiceReferenceA.BuscarRutRequest();
            inValue.Body = new Negocio.ServiceReferenceA.BuscarRutRequestBody();
            inValue.Body.rut = rut;
            return ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).BuscarRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Negocio.ServiceReferenceA.BuscarIdResponse Negocio.ServiceReferenceA.WebServiceAlumnSoap.BuscarId(Negocio.ServiceReferenceA.BuscarIdRequest request) {
            return base.Channel.BuscarId(request);
        }
        
        public Negocio.ServiceReferenceA.EAlumno BuscarId(int Id) {
            Negocio.ServiceReferenceA.BuscarIdRequest inValue = new Negocio.ServiceReferenceA.BuscarIdRequest();
            inValue.Body = new Negocio.ServiceReferenceA.BuscarIdRequestBody();
            inValue.Body.Id = Id;
            Negocio.ServiceReferenceA.BuscarIdResponse retVal = ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).BuscarId(inValue);
            return retVal.Body.BuscarIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.BuscarIdResponse> Negocio.ServiceReferenceA.WebServiceAlumnSoap.BuscarIdAsync(Negocio.ServiceReferenceA.BuscarIdRequest request) {
            return base.Channel.BuscarIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServiceReferenceA.BuscarIdResponse> BuscarIdAsync(int Id) {
            Negocio.ServiceReferenceA.BuscarIdRequest inValue = new Negocio.ServiceReferenceA.BuscarIdRequest();
            inValue.Body = new Negocio.ServiceReferenceA.BuscarIdRequestBody();
            inValue.Body.Id = Id;
            return ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).BuscarIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Negocio.ServiceReferenceA.ActualizarResponse Negocio.ServiceReferenceA.WebServiceAlumnSoap.Actualizar(Negocio.ServiceReferenceA.ActualizarRequest request) {
            return base.Channel.Actualizar(request);
        }
        
        public bool Actualizar(Negocio.ServiceReferenceA.EAlumno eAlumno) {
            Negocio.ServiceReferenceA.ActualizarRequest inValue = new Negocio.ServiceReferenceA.ActualizarRequest();
            inValue.Body = new Negocio.ServiceReferenceA.ActualizarRequestBody();
            inValue.Body.eAlumno = eAlumno;
            Negocio.ServiceReferenceA.ActualizarResponse retVal = ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).Actualizar(inValue);
            return retVal.Body.ActualizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.ActualizarResponse> Negocio.ServiceReferenceA.WebServiceAlumnSoap.ActualizarAsync(Negocio.ServiceReferenceA.ActualizarRequest request) {
            return base.Channel.ActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServiceReferenceA.ActualizarResponse> ActualizarAsync(Negocio.ServiceReferenceA.EAlumno eAlumno) {
            Negocio.ServiceReferenceA.ActualizarRequest inValue = new Negocio.ServiceReferenceA.ActualizarRequest();
            inValue.Body = new Negocio.ServiceReferenceA.ActualizarRequestBody();
            inValue.Body.eAlumno = eAlumno;
            return ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).ActualizarAsync(inValue);
        }
        
        public bool Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Negocio.ServiceReferenceA.MostrarResponse Negocio.ServiceReferenceA.WebServiceAlumnSoap.Mostrar(Negocio.ServiceReferenceA.MostrarRequest request) {
            return base.Channel.Mostrar(request);
        }
        
        public Negocio.ServiceReferenceA.EAlumno[] Mostrar() {
            Negocio.ServiceReferenceA.MostrarRequest inValue = new Negocio.ServiceReferenceA.MostrarRequest();
            inValue.Body = new Negocio.ServiceReferenceA.MostrarRequestBody();
            Negocio.ServiceReferenceA.MostrarResponse retVal = ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).Mostrar(inValue);
            return retVal.Body.MostrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Negocio.ServiceReferenceA.MostrarResponse> Negocio.ServiceReferenceA.WebServiceAlumnSoap.MostrarAsync(Negocio.ServiceReferenceA.MostrarRequest request) {
            return base.Channel.MostrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Negocio.ServiceReferenceA.MostrarResponse> MostrarAsync() {
            Negocio.ServiceReferenceA.MostrarRequest inValue = new Negocio.ServiceReferenceA.MostrarRequest();
            inValue.Body = new Negocio.ServiceReferenceA.MostrarRequestBody();
            return ((Negocio.ServiceReferenceA.WebServiceAlumnSoap)(this)).MostrarAsync(inValue);
        }
    }
}
