//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string NombreCarrera { get; set; }
        public string AreaDeNegocio { get; set; }
        public bool Estado { get; set; }
    }
}
